import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import FloatingBackground from "@/app/components/FloatingBackground"; // Import the animation component

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative bg-[#fce4ec] min-h-screen overflow-hidden`}
      >
        <FloatingBackground /> {/* Adds the animated hearts & flowers */}
        {children}
      </body>
    </html>
  );
}
